# Generated by Django 2.0 on 2018-11-15 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='end',
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='start',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='end',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='roadmap',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='start',
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='reproducibility',
            field=models.ForeignKey(blank=True, help_text='Is this anomaly occurs sometimes or always', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='anomaly_set', to='tracker.Reproducibility', verbose_name='Reproducibility'),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='type',
            field=models.ForeignKey(help_text='Type of anomalie', on_delete=django.db.models.deletion.DO_NOTHING, related_name='anomaly_set', to='tracker.AnomalyCategorie', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ticket',
            field=models.ForeignKey(help_text='Related Ticket', on_delete=django.db.models.deletion.DO_NOTHING, related_name='set_comment', to='tracker.Ticket', verbose_name='ticket'),
        ),
        migrations.AlterField(
            model_name='module',
            name='application',
            field=models.ForeignKey(blank=True, help_text='Related application', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='module_set', to='tracker.Application', verbose_name='Application'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='roadmap',
            field=models.ForeignKey(help_text='Related Roadmap', on_delete=django.db.models.deletion.DO_NOTHING, related_name='sprint', to='tracker.Roadmap', verbose_name='roadmap'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User assigned to the task of resolving this ticket', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tracker_task_set', to=settings.AUTH_USER_MODEL, verbose_name='assigned_to'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='accountable',
            field=models.ForeignKey(blank=True, help_text='MOA leader on this ticket, A in RACI matrix', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tracker_ticket_accountable_set', to=settings.AUTH_USER_MODEL, verbose_name='Person accountable for this ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='application',
            field=models.ForeignKey(blank=True, help_text='Related application', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket_set', to='tracker.Application', verbose_name='Application'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='impact',
            field=models.ForeignKey(help_text='Is resolving this ticket will make a big difference ?', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket_set', to='tracker.Impact', verbose_name='Impact'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='original',
            field=models.ForeignKey(blank=True, help_text='Mark this ticket as a duplicate of:', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='duplicate_set', to='tracker.Ticket', verbose_name='Original ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.ForeignKey(help_text='Is resolving this ticket is game changing ?', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket_set', to='tracker.Priority', verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='responsible',
            field=models.ForeignKey(blank=True, help_text='MOE leader on this ticket, R in RACI matrix', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tracker_ticket_responsible_set', to=settings.AUTH_USER_MODEL, verbose_name='Person in charge of this ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sprint',
            field=models.ForeignKey(blank=True, help_text='Related Sprint', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket_set', to='tracker.Sprint', verbose_name='Sprint'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(help_text='state of the ticket', on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_of_ticket', to='tracker.Status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time_sensitiveness',
            field=models.ForeignKey(help_text='Is resolving this ticket is a matter of emergency or a long ', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket_set', to='tracker.TimeSensitiveness', verbose_name='Time sensitiveness'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='version_released',
            field=models.ForeignKey(blank=True, help_text='The ticket have been released  in version:', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket_released_set', to='tracker.Version', verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='version_targeted',
            field=models.ForeignKey(blank=True, help_text='Aimed version for the release of this ticket', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets_targeted_set', to='tracker.Version', verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Author of the comment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tracker_ticket_comment_set', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='ticket',
            field=models.ForeignKey(blank=True, help_text='Ticket related to this comment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment_set', to='tracker.Ticket', verbose_name='Ticket'),
        ),
        migrations.AlterField(
            model_name='version',
            name='application',
            field=models.ForeignKey(blank=True, help_text='Related application', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='version_set', to='tracker.Application', verbose_name='Application'),
        ),
    ]
