# Generated by Django 2.0 on 2019-02-22 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20181115_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256, verbose_name='label')),
            ],
            options={
                'verbose_name': 'objective',
                'verbose_name_plural': 'objectives',
            },
        ),
        migrations.AlterField(
            model_name='sprint',
            name='roadmap',
            field=models.ForeignKey(blank=True, help_text='Related Roadmap', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sprint', to='tracker.Roadmap', verbose_name='roadmap'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='objective',
            field=models.ForeignKey(blank=True, help_text='Related Objective', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='objective', to='tracker.Objective', verbose_name='objective'),
        ),
    ]
