# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-04 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_related', '0004_dailyevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyEvent',
            fields=[
                ('timerelatedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='time_related.TimeRelatedObject')),
                ('every_x_week', models.CharField(max_length=2, verbose_name='Every')),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
            ],
            bases=('time_related.timerelatedobject',),
        ),
    ]
