# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-04 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_related', '0002_auto_20170904_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timerelatedobject',
            name='daily',
        ),
        migrations.RemoveField(
            model_name='timerelatedobject',
            name='monthly',
        ),
        migrations.RemoveField(
            model_name='timerelatedobject',
            name='weekly',
        ),
        migrations.RemoveField(
            model_name='timerelatedobject',
            name='yearly',
        ),
    ]
