# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-04 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_related', '0003_auto_20170904_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEvent',
            fields=[
                ('timerelatedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='time_related.TimeRelatedObject')),
                ('every_x_day', models.CharField(max_length=2, verbose_name='Every')),
            ],
            bases=('time_related.timerelatedobject',),
        ),
    ]
