# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-04 09:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_related', '0006_auto_20170904_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyevent',
            name='timerelatedobject_ptr',
        ),
        migrations.RemoveField(
            model_name='monthlyevent',
            name='timerelatedobject_ptr',
        ),
        migrations.RemoveField(
            model_name='weeklyevent',
            name='timerelatedobject_ptr',
        ),
        migrations.RemoveField(
            model_name='yearlyevent',
            name='timerelatedobject_ptr',
        ),
        migrations.RemoveField(
            model_name='timerelatedobject',
            name='polymorphic_ctype',
        ),
        migrations.AddField(
            model_name='timerelatedobject',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DailyEvent',
        ),
        migrations.DeleteModel(
            name='MonthlyEvent',
        ),
        migrations.DeleteModel(
            name='WeeklyEvent',
        ),
        migrations.DeleteModel(
            name='YearlyEvent',
        ),
    ]
