# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_related', '0007_auto_20170904_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timerelatedobject',
            name='data',
        ),
    ]
